name: Java CI with Maven

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
          
      - name: Perform the Unit Test Cases
        run: mvn -B test

security:
  needs: test
  name: Security scan using Snyk
  runs-on: ubuntu-latest
  
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: "17"
        distribution: "temurin"
        cache: maven
    
    - name: Install Snyk CLI
      run: |
        npm install -g snyk
        snyk --version
    
    - name: Authenticate Snyk
      run: snyk auth ${{ secrets.SNYK_TOKEN }}
    
    - name: Run Snyk test
      run: snyk test --severity-threshold=high --all-projects
      continue-on-error: true
    
    - name: Run Snyk monitor
      if: github.ref == 'refs/heads/main'
      run: snyk monitor --all-projects
      continue-on-error: true