name: OWASP ZAP Security Scan

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

jobs:
  zap-baseline-scan:
    name: ZAP DAST Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build application
        run: ./mvnw clean package -DskipTests

      - name: Build Docker image
        run: docker build -t cicd-demo:test .

      - name: Run application container
        run: |
          docker run -d -p 5000:5000 --name cicd-demo-app cicd-demo:test
          echo "Waiting for application to start..."
          sleep 10
          timeout 90 bash -c 'until curl -f http://localhost:5000/ 2>/dev/null; do echo "Waiting..."; sleep 3; done' || echo "Proceeding with scan"

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:5000'
          cmd_options: '-a'

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-scan-report
          path: report_html.html

      - name: Stop application container
        if: always()
        run: docker stop cicd-demo-app && docker rm cicd-demo-app